import React from 'react';
import './global.css';

export const metadata = {
  title: 'Welcome to vendemas-landing-web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
